import {
  useEffect
} from 'react';
import Head from 'next/head'
import { Web3ReactProvider } from '@web3-react/core'
import { ThemeProvider } from '@material-ui/core/styles';
import Web3 from 'web3'
import CssBaseline from '@material-ui/core/CssBaseline';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import theme from '../theme';


import '../styles/globals.css'


function getLibrary(provider) {
  return new Web3(provider)
}

function MyApp({ Component, pageProps }) {

  useEffect(() => {
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);

  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Head>
          <title>Quiz App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container maxWidth="fixed">
          <Grid  container spacing={0} direction="column" alignItems="center" justifyContent="center" style={{ minHeight: '100vh' }}>
            <Component {...pageProps} />
          </Grid>
        </Container>
      </ThemeProvider>
    </Web3ReactProvider>
  )
}

export default MyApp
