import { useEffect ,useCallback } from 'react'
import Head from 'next/head'
import { useWeb3React } from '@web3-react/core'
import { connector } from '../config/web3'

import Button from '@mui/material/Button';

import styles from '../styles/Home.module.css'

export const getStaticProps = async () => {

  const abiRes = await fetch('https://ratherlabs-challenges.s3.sa-east-1.amazonaws.com/survey-abi.json')
  const abi = await abiRes.json()

  const surveyRes = await fetch('https://ratherlabs-challenges.s3.sa-east-1.amazonaws.com/survey-sample.json')
  const survey = await surveyRes.json()

  return {
    props: {
      abi: abi,
      survey: survey
    }
  }

}


export default function Home({abi, survey}) {

  console.log(abi)
  console.log(survey)

  const { activate, active, account, chainId, deactivate, error } = useWeb3React()
  
  const connect = useCallback(() => {
    activate(connector)
    localStorage.setItem('previuoslyConnected', true)
  }, [activate])

  const disconnect = () => {
    deactivate()
    localStorage.removeItem('previuoslyConnected')
  }

  useEffect(() => {
    if (localStorage.getItem('previuoslyConnected') === 'true')
      connect()
  }, [connect])

  const blockChainName = chainId === 1 ? 'Ethereum' : 'Otra que no es Ethereum'

  if (error) {
    return (
      <>
        <h1>Upps! Hubo un error durante la conexion:</h1>
        <p>{error.message}</p>
      </>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome ~
          to Web3
        </h1>

        {
          active
            ? 
              <>
                <Button variant="contained" onClick={disconnect}>Desconectar!</Button >
                <h2>
                  Estas conectado a {blockChainName}!
                  <br />
                  Tu cuenta es: {account}
                </h2>
              </>
            : <Button variant="contained" onClick={connect}>Conectar!</Button >
        }

        
      </main>
    </div>
  )
}
